version: '3'
services:
  db:
    hostname: db
    image: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DRIVER=postgresql
  app:
    tty: true
    command: sh -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - 8000:8000