# Generated by Django 3.2.4 on 2021-06-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_brom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brom',
        ),
    ]
