# Generated by Django 3.2.4 on 2021-06-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20210626_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prodile_image',
            new_name='profile_image',
        ),
    ]
